apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shutdown-ope-containers
  namespace: ope-test
spec:
  stepTemplate:
    env:
      - name: "HOME" 
        value: "/tekton/home"
  steps:
    - name: shutdown-ope-containers
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      workingDir: /scripts
      script: |
        #!/bin/sh
        
        set_time=1 mins

        time_limit=$(($(date -u +"%s") - $(date -d '-$set_time' +%s)))

        running_notebooks=$(oc get notebook -o custom-columns=:metadata.name)

        for notebook in $running_notebooks; do

          start_time=$(oc get notebook $notebook -o jsonpath='{.status.containerState.running.startedAt}')
            
          running_time=$(($(date -u +"%s") - $(date -u -d "$start_time" +"%s")))
          
          if [ "$running_time" -gt "$time_limit" ]; then
            echo "Shutting down pod $notebook"
            oc delete notebook $notebook
            oc delete pvc $notebook
          fi 
        done
